# Generated by Django 2.0 on 2018-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('comp_id', models.CharField(default='16CA6000_0', max_length=20, primary_key=True, serialize=False)),
                ('comp_type', models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=15)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('hall', models.IntegerField()),
                ('room', models.DecimalField(decimal_places=0, max_digits=3)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=11)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
