# Generated by Django 2.0 on 2018-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_st_16ca6001'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_type', models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('hall', models.IntegerField()),
                ('room', models.DecimalField(decimal_places=0, max_digits=3)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='st_16ca6001',
            name='comp_type',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=10),
        ),
    ]
