# Generated by Django 2.0 on 2018-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20180323_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='dummy',
        ),
        migrations.RemoveField(
            model_name='st_16ca6001',
            name='comp_id',
        ),
    ]
