# Generated by Django 2.0 on 2018-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_st_16ca6032'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_people',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('admin_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
