# Generated by Django 2.0 on 2018-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20180323_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy',
            name='id',
        ),
        migrations.AddField(
            model_name='dummy',
            name='comp_id',
            field=models.CharField(default='16CA6000_0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
