# Generated by Django 2.0 on 2018-03-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_admin_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_people',
            old_name='admin_name',
            new_name='user_name',
        ),
    ]
