# Generated by Django 2.0 on 2018-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20180328_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Seen', 'Seen'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Registered', max_length=15),
        ),
    ]
