# Generated by Django 2.0 on 2018-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20180325_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='st_16CA6032',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comp_type', models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('hall', models.IntegerField()),
                ('room', models.DecimalField(decimal_places=0, max_digits=3)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
