# Generated by Django 2.0 on 2018-03-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_elec_emp_furni_emp_water_emp'),
        ('complaint', '0006_dummy_status'),
    ]

    operations = [
    ]
