# Generated by Django 2.0 on 2018-03-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_merge_20180330_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_16ca6032',
            name='comp_type',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=15),
        ),
    ]
