# Generated by Django 2.0 on 2018-03-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_st_16ca6032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='st_16CA6032',
        ),
    ]
