# Generated by Django 2.0 on 2018-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_st_16ca6032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='st_16CA6032',
        ),
        migrations.AlterField(
            model_name='dummy',
            name='comp_type',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
