# Generated by Django 2.0 on 2018-03-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_st_16ca6032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_16ca6032',
            name='status',
            field=models.CharField(default='Registered', max_length=10),
        ),
    ]
