# Generated by Django 2.0 on 2018-03-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_delete_st_16ca6023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='st_16CA6032',
        ),
    ]
