# Generated by Django 2.0 on 2018-03-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0013_delete_st_16ca6032'),
    ]

    operations = [
        migrations.CreateModel(
            name='st_16CA6023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comp_type', models.CharField(choices=[('Furniture', 'Furniture'), ('Electricity', 'Electricity'), ('Water', 'Water')], max_length=15)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Seen', 'Seen'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Registered', max_length=15)),
            ],
        ),
    ]
