# Generated by Django 2.0 on 2018-03-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0018_st_16ca6032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='st_16CA6032',
        ),
    ]
