# Generated by Django 2.0 on 2018-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0020_st_16ca6032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp',
        ),
        migrations.AddField(
            model_name='dummy',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
